In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from sklearn.preprocessing import *
from sklearn.model_selection import *
from tensorflow import keras
from sklearn.metrics import *

In [2]:
df = pd.read_csv('datasets/Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
le = LabelEncoder()

In [5]:
df['Geography'] = le.fit_transform(df['Geography'])
df['Gender'] = le.fit_transform(df['Gender'])

In [7]:
df = df.drop(['RowNumber','Surname','CustomerId'],axis=1)

In [8]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,772,1,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,0,0,28,4,130142.79,1,1,0,38190.78,0

In [9]:
x = df.drop('Exited',axis=1)
y = df['Exited']

In [10]:
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,0,0,42,2,0.00,1,1,1,101348.88
1,608,2,0,41,1,83807.86,1,0,1,112542.58
2,502,0,0,42,8,159660.80,3,1,0,113931.57
3,699,0,0,39,1,0.00,2,0,0,93826.63
4,850,2,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64
9996,516,0,1,35,10,57369.61,1,1,1,101699.77
9997,709,0,0,36,7,0.00,1,0,1,42085.58
9998,772,1,1,42,3,75075.31,2,1,0,92888.52
9999,792,0,0,28,4,130142.79,1,1,0,38190.78

In [11]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)

In [14]:
model = keras.Sequential([
    keras.layers.Dense(units=13,activation='relu'),
    keras.layers.Dense(units=15,activation='relu'),
    keras.layers.Dense(units=1,activation='sigmoid')
])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7946
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4547 - accuracy: 0.7979
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4297 - accuracy: 0.8041
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4121 - accuracy: 0.8267
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3980 - accuracy: 0.8365
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3835 - accuracy: 0.8418
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3689 - accuracy: 0.8511
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3572 - accuracy: 0.8554
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3505 - accuracy: 0.8577
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3463 - accuracy: 0.8597
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3433 - accuracy: 0.8593
Epoch 12/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3413 - accuracy: 0.8605
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3397 - accuracy: 0.8593
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3380 - accuracy: 0.8633
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3370 - accuracy: 0.8624
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3365 - accuracy: 0.8629
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3354 - accuracy: 0.8627
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3354 - accuracy: 0.8616
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3341 - accuracy: 0.8634
Epoch 20/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3340 - accuracy: 0.8645
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3330 - accuracy: 0.8644
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3325 - accuracy: 0.8639
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3328 - accuracy: 0.8631
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3320 - accuracy: 0.8630
Epoch 25/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3319 - accuracy: 0.8652
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3317 - accuracy: 0.8635
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3313 - accuracy: 0.8630
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3306 - accuracy: 0.8633
Epoch 29/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3312 - accuracy: 0.8645
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3304 - accuracy: 0.8635
Epoch 31/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3302 - accuracy: 0.8631
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3305 - accuracy: 0.8636
Epoch 33/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3304 - accuracy: 0.8636
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3294 - accuracy: 0.8643
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3293 - accuracy: 0.8645
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3291 - accuracy: 0.8641
Epoch 37/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3289 - accuracy: 0.8651
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3291 - accuracy: 0.8660
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3285 - accuracy: 0.8649
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3281 - accuracy: 0.8624
Epoch 41/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3283 - accuracy: 0.8646
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3285 - accuracy: 0.8639
Epoch 43/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3279 - accuracy: 0.8640
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3284 - accuracy: 0.8646
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3283 - accuracy: 0.8622
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3277 - accuracy: 0.8645
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3278 - accuracy: 0.8650
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3271 - accuracy: 0.8643
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3273 - accuracy: 0.8644
Epoch 50/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3275 - accuracy: 0.8644
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3271 - accuracy: 0.8645
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3274 - accuracy: 0.8644
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3274 - accuracy: 0.8645
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3268 - accuracy: 0.8654
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3271 - accuracy: 0.8649
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3272 - accuracy: 0.8639
Epoch 57/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3267 - accuracy: 0.8652
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3265 - accuracy: 0.8644
Epoch 59/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3265 - accuracy: 0.8652
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3264 - accuracy: 0.8639
Epoch 61/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3266 - accuracy: 0.8643
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3261 - accuracy: 0.8634
Epoch 63/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8646
Epoch 64/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3260 - accuracy: 0.8643
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3263 - accuracy: 0.8652
Epoch 66/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3255 - accuracy: 0.8640
Epoch 67/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3252 - accuracy: 0.8661
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3257 - accuracy: 0.8652
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3256 - accuracy: 0.8640
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3254 - accuracy: 0.8661
Epoch 71/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3254 - accuracy: 0.8645
Epoch 72/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3252 - accuracy: 0.8650
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3255 - accuracy: 0.8639
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3249 - accuracy: 0.8660
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3250 - accuracy: 0.8652
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3247 - accuracy: 0.8658
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3250 - accuracy: 0.8655
Epoch 78/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3248 - accuracy: 0.8648
Epoch 79/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3247 - accuracy: 0.8641
Epoch 80/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3248 - accuracy: 0.8624
Epoch 81/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3248 - accuracy: 0.8639
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3243 - accuracy: 0.8643
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3248 - accuracy: 0.8635
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3241 - accuracy: 0.8654
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3232 - accuracy: 0.8652
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3240 - accuracy: 0.8631
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3238 - accuracy: 0.8651
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3235 - accuracy: 0.8661
Epoch 89/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3244 - accuracy: 0.8648
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3235 - accuracy: 0.8666
Epoch 91/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3235 - accuracy: 0.8662
Epoch 92/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3238 - accuracy: 0.8659
Epoch 93/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3238 - accuracy: 0.8643
Epoch 94/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3230 - accuracy: 0.8658
Epoch 95/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3232 - accuracy: 0.8644
Epoch 96/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3226 - accuracy: 0.8662
Epoch 97/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3227 - accuracy: 0.8670
Epoch 98/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3228 - accuracy: 0.8665
Epoch 99/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3228 - accuracy: 0.8652
Epoch 100/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3233 - accuracy: 0.8660

In [15]:
model.evaluate(x_test,y_test)

63/63 [==============================] - 0s 2ms/step - loss: 0.3530 - accuracy: 0.8580

[0.3529823422431946, 0.8579999804496765]

In [16]:
pred = model.predict(x_test)

In [17]:
pred

array([[0.1082103 ],
       [0.04103971],
       [0.08465728],
       ...,
       [0.13193655],
       [0.04862678],
       [0.4821077 ]], dtype=float32)

In [18]:
y_pred=[]
for e in pred:
    if e>0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [19]:
y_pred

[0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [20]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1580
           1       0.77      0.46      0.58       420

    accuracy                           0.86      2000
   macro avg       0.82      0.71      0.75      2000
weighted avg       0.85      0.86      0.84      2000

In [21]:
print(accuracy_score(y_test,y_pred))

0.858

In [22]:
print(confusion_matrix(y_test,y_pred))

[[1521   59]
 [ 225  195]]

In [4]:
model = keras.Sequential([
    keras.layers.Dense(units=15,activation="relu"),
    keras.layers.Dense(units=13,activation="relu"),
    keras.layers.Dense(units=13,activation="sigmoid")
]
)
model.compile(optimizers='adam',loss='binary_crossentropy',metrics='accuracy')
model.fit(x_train,y_train,epochs=100)

NameError: name 'keras' is not defined